[package]
name = "lottery-esdt"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/lottery.rs"

[dependencies.multiversx-sc]
version = "=0.45.2"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.45.2"
