[package]
name = "multisig-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.multisig]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.1"
