[package]
name = "multisig-meta"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[dependencies.multisig]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.45.2"
default-features = false
