[package]
name = "lottery-esdt-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.lottery-esdt]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.43.4"
