[package]
name = "multisig"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/multisig.rs"

[dependencies.multiversx-sc]
version = "=0.45.2"

[dependencies.multiversx-sc-modules]
version = "=0.45.2"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.45.2"

