name: CI

on:
  pull_request:

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@bf2fba12098fcbc7e297c9df12072c8c6c8d47a4
    with:
      rust-toolchain: nightly-2023-05-26
      vmtools-version: v1.4.60
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
