name: Test (attaching to existing release)

on:
  release:
    types: [published]

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@reproducible-builds-24
    with:
      image_tag: v4.1.0
      attach_to_existing_release: true
